// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bzybntnxehfjsrenarrj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ6eWJudG54ZWhmanNyZW5hcnJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4MDc3MTIsImV4cCI6MjA2NjM4MzcxMn0.RJX1TPsjQi0_y_0EkEkyAoKgU8xv7x4hIIntkqtQgF8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);